apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/postgre-sealed-secret.yaml
- manifests/postgre-persistentvolume.yaml
- manifests/postgre-configmap.yaml
- manifests/postgre-service.yaml
- manifests/postgre-statefulset.yaml
- manifests/nats-svc.yaml
- manifests/nats-statefulset.yaml
- manifests/ingress.yaml



