apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/fe-deployment.yaml
- manifests/fe-service.yaml
- manifests/fe-horizontalpodautoscaler.yaml
images:
- name: FRONTEND-IMAGE
  newName: epylkkan/training_kubernetes_devops:402-11todofront



