apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/epylkkan/devops-with-kubernetes_hy2021_cluster-definitions_4.07
  ref:
    branch: master
