apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/epylkkan/kube-cluster-dwk/backend
  ref:
    branch: master
