apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/be_rollout.yaml
- manifests/be_service.yaml
- manifests/be_horizontalpodautoscaler.yaml
images:
- name: BACKEND-IMAGE
  newName: epylkkan/training_kubernetes_devops:406-73todoback



