apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/wiki-deployment.yaml
- manifests/wiki-service.yaml
- manifests/wiki-cronjob.yaml
- manifests/wiki-horizontalpodautoscaler.yaml
images:
- name: WIKI-IMAGE
  newName: epylkkan/training_kubernetes_devops:402wiki



