apiVersion: v1
kind: Service
metadata:
  name: todo-front-svc
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: todo-front
  ports:
    - port: 2345
      name: todo-front
      protocol: TCP
      targetPort: 3000
