apiVersion: v1
kind: Service
metadata:
  name: todo-wiki-svc
  namespace: todo
spec:
  type: ClusterIP
  selector:
    app: todo-wiki
  ports:
    - port: 2347
      name: todo-wiki
      protocol: TCP
      targetPort: 3005
