name: dwk training frontend 4.08 gitops app

on:
  workflow_dispatch:
  #push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/gitops-gha_fe.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build and push
    #- name: Publish to Registry
    #  uses: docker/build-push-action@v2
    #  with:
    #    repository: epylkkan/training_kubernetes_devops
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    #    tags: ${{ github.sha }}
    #    path: frontend


    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
       context: .
       push: ${{ GitHub.event_name != 'pull_request' }}
       #tags: ${{ steps.meta.outputs.tags }}
       tags: ${{ github.sha }}
       #labels: ${{ steps.meta.outputs.labels }}


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: frontend
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Update yamls
    - name: Update yamls
      working-directory: frontend
      run: |-
        ./kustomize edit set image IMAGE_PLACEHOLDER=epylkkan/training_kubernetes_devops/gitops-fe-408:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: 'frontend/kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}